fix: updated vind version and added validation test

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -19,7 +19,7 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      # 1. Build & Push עם תיוג דינמי
+     
       - name: Log in to GHCR
         uses: docker/login-action@v3
         with:
@@ -35,7 +35,6 @@ jobs:
           docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$TAG
           echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV
 
-      # 2. Cluster Provisioning עם vind
       - name: Install vind
         run: |
           curl -L -o vind https://github.com/loft-sh/vind/releases/download/v0.0.12/vind-linux-amd64
@@ -46,7 +45,6 @@ jobs:
 
           vind create cluster my-cluster
 
-      # 3. Deployment עם Helm
       - name: Deploy with Helm
         run: |
           helm dependency update ./my-app-chart
@@ -54,3 +52,20 @@ jobs:
             --set image.repository=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} \
             --set image.tag=${{ env.IMAGE_TAG }} \
             --wait --timeout 5m
+
+      - name: Validation Test
+        run: |
+          echo "Waiting for application to be ready..."
+          # מנגנון המתנה עד שהאפליקציה תעלה
+          ATTEMPTS=0
+          MAX_ATTEMPTS=15
+          until curl -s http://localhost:30001 | grep "200 OK"; do
+            echo "Waiting... ($ATTEMPTS/$MAX_ATTEMPTS)"
+            sleep 10
+            ATTEMPTS=$((ATTEMPTS+1))
+            if [ $ATTEMPTS -eq $MAX_ATTEMPTS ]; then
+              echo "App failed to start!"
+              exit 1
+            fi
+          done
+          echo "Success! Application is up."
